{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Memory usage per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job)(\n  container_memory_working_set_bytes{namespace=\"auth-ns\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod count per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count by (job)(\n  up\n)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (job)(\n  rate(http_requests_total[1m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job)(\n  rate(container_cpu_usage_seconds_total{namespace=\"auth-ns\"}[5m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests (Volume)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "sum(http_requests_total)\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, job)(\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}