{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOTAL Cost per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace)(\n    rate(container_cpu_usage_seconds_total{namespace!=\"\"}[5m])\n  ) * 0.048\n)\n+\n(\n  sum by (namespace)(\n    container_memory_working_set_bytes{namespace!=\"\"}\n  ) / 1024 / 1024 / 1024 * 0.01\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cost / Namespace ($/hr approx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace)(\n  rate(container_cpu_usage_seconds_total[5m])\n) * 0.048\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Cost / Namespace ($/hr approx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\n  container_memory_working_set_bytes{namespace!=\"\"}\n) / 1024 / 1024 / 1024 * 0.01\n",
     "legendFormat": "{{namespace}} - Memory"
    }
   ]
  },
  {
   "title": "Pod Count per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by (namespace)(\n  kube_pod_info\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}